#services (neo4j, airflow etc)

version: "3.9"

services:
  neo4j:
    image: neo4j:${NEO4J_VERSION}
    container_name: neo4j
    environment:
      - NEO4J_AUTH=none    # disables auth for local dev (as required)
    ports:
      - "${NEO4J_HTTP_PORT}:7474"
      - "${NEO4J_BOLT_PORT}:7687"
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    restart: unless-stopped

volumes:
  neo4j_data:
  neo4j_logs:
